create table contact (
  id                            bigint generated by default as identity (start with 1)  not null,
  firstname                     varchar(255),
  name                          varchar(255),
  birthdate                     timestamp,
  email                         varchar(255),
  constraint pk_contact primary key (id)
);

